import type { Lead } from '../types/lead';

// Real data from Pipedrive via Nekt data lake (pipedrive_deals_readable)
export const realLeads: Lead[] = [
  {
    id: 255628,
    titulo: "Caroline Watambak Lisboa - Ponta das Canas Spot II",
    status: "open",
    valor: 266666,
    nome_investidor: "Caroline Watambak Lisboa",
    telefone: "+353833461874",
    e_mail: "carolinewlisbo@icloud.com",
    profissao: "Empresária",
    estado_civil: "Solteira",
    nacionalidade: "Brasileira",
    cidade_onde_fica_o_imovel: "Florianópolis",
    canal: "Indicação de Corretor",
    origem: "API",
    tipo_de_venda: "Parceiro",
    empreendimento: "Ponta das Canas Spot II",
    plano: "",
    pre_vendedor_a: "",
    deal_owner_name: "Equipe Comercial",
    data_da_reuniao: "2026-03-30",
    data_de_qualificacao: "2026-03-30",
    observacoes_longo: "Nacionalidade: brasileiro | Profissão: COZINHEIRA | Investidora interessada em imóvel de alto padrão na praia",
    total_de_atividades: 4,
    atividades_concluidas: 4,
    notes_count: 2,
    numero_de_mensagens_de_e_mail: 0,
    etapa: "192",
    funil: "Vendas",
    negocio_criado_em: "2026-03-28",
    atualizado_em: "2026-03-31",
    score: 72,
  },
  {
    id: 254636,
    titulo: "Thais Burmeister - Ponta das Canas Spot II",
    status: "open",
    valor: 306934,
    nome_investidor: "Thais Burmeister Tirelli Gomes dos Santos",
    telefone: "+5547999953186",
    e_mail: "thais.burmeister@gmail.com",
    profissao: "Designer de Joias",
    estado_civil: "Solteira",
    nacionalidade: "Brasileira",
    cidade_onde_fica_o_imovel: "Florianópolis",
    canal: "Indicação de Corretor",
    origem: "API",
    tipo_de_venda: "Parceiro",
    empreendimento: "Ponta das Canas Spot II",
    plano: "",
    pre_vendedor_a: "",
    deal_owner_name: "Equipe Comercial",
    data_da_reuniao: "2026-03-28",
    data_de_qualificacao: "2026-03-25",
    observacoes_longo: "Designer de joias com interesse em investimento imobiliário para renda passiva",
    total_de_atividades: 3,
    atividades_concluidas: 2,
    notes_count: 1,
    numero_de_mensagens_de_e_mail: 1,
    etapa: "185",
    funil: "Vendas",
    negocio_criado_em: "2026-03-20",
    atualizado_em: "2026-03-30",
    score: 65,
  },
  {
    id: 250824,
    titulo: "Glauco Gioda Marques - Ponta das Canas Spot II",
    status: "open",
    valor: 291149,
    nome_investidor: "Glauco Gioda Marques",
    telefone: "+5555999101709",
    e_mail: "glaucom@hotmail.com",
    profissao: "Empresário",
    estado_civil: "Solteiro",
    nacionalidade: "Brasileiro",
    cidade_onde_fica_o_imovel: "Florianópolis",
    canal: "Indicação",
    origem: "Indicação",
    tipo_de_venda: "Interna",
    empreendimento: "Ponta das Canas Spot II",
    plano: "",
    pre_vendedor_a: "",
    deal_owner_name: "Equipe Comercial",
    data_da_reuniao: "2026-03-25",
    data_de_qualificacao: "2026-03-15",
    observacoes_longo: "Empresário do sul, já conhece a região de Florianópolis. Interesse em diversificar portfólio com imóvel de temporada",
    total_de_atividades: 16,
    atividades_concluidas: 15,
    notes_count: 5,
    numero_de_mensagens_de_e_mail: 3,
    etapa: "200",
    funil: "Vendas",
    negocio_criado_em: "2026-02-10",
    atualizado_em: "2026-03-29",
    score: 85,
  },
  {
    id: 249237,
    titulo: "Marcelo Meza da Silva - Ponta das Canas Spot II",
    status: "open",
    valor: 299918,
    nome_investidor: "Marcelo Meza da Silva",
    telefone: "+5553999710913",
    e_mail: "marcelo.mezadasilva@gmail.com",
    profissao: "Financiário",
    estado_civil: "Casado",
    nacionalidade: "Brasileiro",
    cidade_onde_fica_o_imovel: "Florianópolis",
    canal: "Marketing",
    origem: "Marketing Digital",
    tipo_de_venda: "Interna",
    empreendimento: "Ponta das Canas Spot II",
    plano: "",
    pre_vendedor_a: "",
    deal_owner_name: "Equipe Comercial",
    data_da_reuniao: "2026-03-22",
    data_de_qualificacao: "2026-03-10",
    observacoes_longo: "Profissional do mercado financeiro, casado, busca investimento seguro com boa rentabilidade. Já possui outros investimentos imobiliários",
    total_de_atividades: 16,
    atividades_concluidas: 15,
    notes_count: 4,
    numero_de_mensagens_de_e_mail: 5,
    etapa: "200",
    funil: "Vendas",
    negocio_criado_em: "2026-02-05",
    atualizado_em: "2026-03-28",
    score: 91,
  },
];
