import type { Lead } from '../types/lead';

// Real data from Pipedrive via Nekt data lake (pipedrive_deals_readable)
export const realLeads: Lead[] = [
  // --- Original leads with full qualification data ---
  {
    id: 255628,
    titulo: "Caroline Watambak Lisboa - Ponta das Canas Spot II",
    status: "open",
    valor: 266666,
    nome_investidor: "Caroline Watambak Lisboa",
    telefone: "+353833461874",
    e_mail: "carolinewlisbo@icloud.com",
    profissao: "Empresária",
    estado_civil: "Solteira",
    nacionalidade: "Brasileira",
    cidade_onde_fica_o_imovel: "Florianópolis, SC",
    canal: "Indicação de Corretor",
    origem: "API",
    tipo_de_venda: "Parceiro",
    empreendimento: "Ponta das Canas Spot II",
    plano: "",
    pre_vendedor_a: "",
    deal_owner_name: "Equipe Comercial",
    data_da_reuniao: "2026-03-30",
    data_de_qualificacao: "2026-03-30",
    observacoes_longo: "Empresária interessada em imóvel de alto padrão na praia para investimento.",
    total_de_atividades: 4,
    atividades_concluidas: 4,
    notes_count: 2,
    numero_de_mensagens_de_e_mail: 0,
    etapa: "Reunião Agendada",
    funil: "Vendas",
    negocio_criado_em: "2026-03-28",
    atualizado_em: "2026-03-31",
    score: 72,
  },
  {
    id: 254636,
    titulo: "Thais Burmeister - Ponta das Canas Spot II",
    status: "open",
    valor: 306934,
    nome_investidor: "Thais Burmeister Tirelli Gomes dos Santos",
    telefone: "+5547999953186",
    e_mail: "thais.burmeister@gmail.com",
    profissao: "Designer de Joias",
    estado_civil: "Solteira",
    nacionalidade: "Brasileira",
    cidade_onde_fica_o_imovel: "Florianópolis, SC",
    canal: "Indicação de Corretor",
    origem: "API",
    tipo_de_venda: "Parceiro",
    empreendimento: "Ponta das Canas Spot II",
    plano: "",
    pre_vendedor_a: "",
    deal_owner_name: "Equipe Comercial",
    data_da_reuniao: "2026-03-28",
    data_de_qualificacao: "2026-03-25",
    observacoes_longo: "Designer de joias com interesse em investimento imobiliário para renda passiva.",
    total_de_atividades: 3,
    atividades_concluidas: 2,
    notes_count: 1,
    numero_de_mensagens_de_e_mail: 1,
    etapa: "Qualificação",
    funil: "Vendas",
    negocio_criado_em: "2026-03-20",
    atualizado_em: "2026-03-30",
    score: 65,
  },
  {
    id: 250824,
    titulo: "Glauco Gioda Marques - Ponta das Canas Spot II",
    status: "open",
    valor: 291149,
    nome_investidor: "Glauco Gioda Marques",
    telefone: "+5555999101709",
    e_mail: "glaucom@hotmail.com",
    profissao: "Empresário",
    estado_civil: "Solteiro",
    nacionalidade: "Brasileiro",
    cidade_onde_fica_o_imovel: "Florianópolis, SC",
    canal: "Indicação",
    origem: "Indicação",
    tipo_de_venda: "Interna",
    empreendimento: "Ponta das Canas Spot II",
    plano: "",
    pre_vendedor_a: "",
    deal_owner_name: "Equipe Comercial",
    data_da_reuniao: "2026-03-25",
    data_de_qualificacao: "2026-03-15",
    observacoes_longo: "Empresário do sul, já conhece a região de Florianópolis. Interesse em diversificar portfólio com imóvel de temporada.",
    total_de_atividades: 16,
    atividades_concluidas: 15,
    notes_count: 5,
    numero_de_mensagens_de_e_mail: 3,
    etapa: "Negociação",
    funil: "Vendas",
    negocio_criado_em: "2026-02-10",
    atualizado_em: "2026-03-29",
    score: 85,
  },
  {
    id: 249237,
    titulo: "Marcelo Meza da Silva - Ponta das Canas Spot II",
    status: "open",
    valor: 299918,
    nome_investidor: "Marcelo Meza da Silva",
    telefone: "+5553999710913",
    e_mail: "marcelo.mezadasilva@gmail.com",
    profissao: "Financiário",
    estado_civil: "Casado",
    nacionalidade: "Brasileiro",
    cidade_onde_fica_o_imovel: "Florianópolis, SC",
    canal: "Marketing",
    origem: "Marketing Digital",
    tipo_de_venda: "Interna",
    empreendimento: "Ponta das Canas Spot II",
    plano: "",
    pre_vendedor_a: "",
    deal_owner_name: "Equipe Comercial",
    data_da_reuniao: "2026-03-22",
    data_de_qualificacao: "2026-03-10",
    observacoes_longo: "Profissional do mercado financeiro, casado, busca investimento seguro com boa rentabilidade. Já possui outros investimentos imobiliários.",
    total_de_atividades: 16,
    atividades_concluidas: 15,
    notes_count: 4,
    numero_de_mensagens_de_e_mail: 5,
    etapa: "Negociação",
    funil: "Vendas",
    negocio_criado_em: "2026-02-05",
    atualizado_em: "2026-03-28",
    score: 91,
  },

  // --- Leads de hoje (01/04/2026) — reuniões do dia ---
  {
    id: 220411,
    titulo: "Juliano Boscardin",
    status: "open",
    valor: 0,
    nome_investidor: "Juliano Boscardin",
    telefone: "+5555999121066",
    e_mail: "",
    profissao: "",
    estado_civil: "",
    nacionalidade: "",
    cidade_onde_fica_o_imovel: "",
    canal: "Marketing",
    origem: "API",
    tipo_de_venda: "Interna",
    empreendimento: "Foz Spot",
    plano: "",
    pre_vendedor_a: "",
    deal_owner_name: "",
    data_da_reuniao: "2026-01-14",
    data_de_qualificacao: "",
    observacoes_longo: "",
    total_de_atividades: 1,
    atividades_concluidas: 0,
    notes_count: 6,
    numero_de_mensagens_de_e_mail: 0,
    etapa: "FUP",
    funil: "Mercado",
    negocio_criado_em: "2026-01-14",
    atualizado_em: "2026-03-06",
    score: 0,
  },
  {
    id: 253505,
    titulo: "Silmara",
    status: "open",
    valor: 0,
    nome_investidor: "Silmara",
    telefone: "",
    e_mail: "",
    profissao: "",
    estado_civil: "",
    nacionalidade: "",
    cidade_onde_fica_o_imovel: "Bombinhas, SC",
    canal: "Indicação de Franquia",
    origem: "API",
    tipo_de_venda: "",
    empreendimento: "",
    plano: "",
    pre_vendedor_a: "",
    deal_owner_name: "",
    data_da_reuniao: "2026-04-01",
    data_de_qualificacao: "2026-03-25",
    observacoes_longo: "Lead está com dificuldades para acessar a reunião por áudio no WhatsApp e vai tentar pelo computador.",
    total_de_atividades: 6,
    atividades_concluidas: 5,
    notes_count: 8,
    numero_de_mensagens_de_e_mail: 0,
    etapa: "Reunião Agendada",
    funil: "Comercial SZS",
    negocio_criado_em: "2026-03-24",
    atualizado_em: "2026-04-01",
    score: 0,
  },
  {
    id: 254400,
    titulo: "Priscila Dalpiaz",
    status: "open",
    valor: 0,
    nome_investidor: "Priscila Dalpiaz",
    telefone: "",
    e_mail: "piloh10@gmail.com",
    profissao: "",
    estado_civil: "",
    nacionalidade: "",
    cidade_onde_fica_o_imovel: "Blumenau, SC",
    canal: "Marketing",
    origem: "API",
    tipo_de_venda: "",
    empreendimento: "",
    plano: "",
    pre_vendedor_a: "",
    deal_owner_name: "",
    data_da_reuniao: "2026-04-01",
    data_de_qualificacao: "2026-03-28",
    observacoes_longo: "",
    total_de_atividades: 18,
    atividades_concluidas: 15,
    notes_count: 5,
    numero_de_mensagens_de_e_mail: 0,
    etapa: "Contatados",
    funil: "Comercial SZS",
    negocio_criado_em: "2026-03-26",
    atualizado_em: "2026-04-01",
    score: 0,
  },
  {
    id: 255567,
    titulo: "Júlio César Ponte",
    status: "open",
    valor: 0,
    nome_investidor: "Júlio César Ponte",
    telefone: "",
    e_mail: "jgmariz@gmail.com",
    profissao: "Cliente SZN",
    estado_civil: "",
    nacionalidade: "",
    cidade_onde_fica_o_imovel: "Brasília, DF",
    canal: "Cliente SZN",
    origem: "API",
    tipo_de_venda: "",
    empreendimento: "",
    plano: "",
    pre_vendedor_a: "",
    deal_owner_name: "",
    data_da_reuniao: "2026-04-01",
    data_de_qualificacao: "2026-03-30",
    observacoes_longo: "Lead possui outro imóvel (Itacaré SPOT) que ainda não foi entregue. A reunião será com a noiva do lead, Jéssica Mariz, pois ela mora no apartamento e tem mais informações.",
    total_de_atividades: 6,
    atividades_concluidas: 3,
    notes_count: 4,
    numero_de_mensagens_de_e_mail: 0,
    etapa: "Reunião Agendada",
    funil: "Comercial SZS",
    negocio_criado_em: "2026-03-30",
    atualizado_em: "2026-04-01",
    score: 0,
  },
  {
    id: 256164,
    titulo: "WSP Empreendimentos - Salvador Spot 1302",
    status: "open",
    valor: 284721,
    nome_investidor: "WSP Empreendimentos e Participações LTDA",
    telefone: "",
    e_mail: "",
    profissao: "Pessoa Jurídica",
    estado_civil: "",
    nacionalidade: "",
    cidade_onde_fica_o_imovel: "Salvador, BA",
    canal: "Indicação de Corretor",
    origem: "API",
    tipo_de_venda: "Parceiro",
    empreendimento: "Salvador Spot",
    plano: "",
    pre_vendedor_a: "",
    deal_owner_name: "",
    data_da_reuniao: "2026-04-01",
    data_de_qualificacao: "2026-04-01",
    observacoes_longo: "Cota 1302 - repasse. Unidade de alto valor para empresa investidora.",
    total_de_atividades: 3,
    atividades_concluidas: 1,
    notes_count: 0,
    numero_de_mensagens_de_e_mail: 0,
    etapa: "Reunião Agendada",
    funil: "Ponto de Vendas",
    negocio_criado_em: "2026-04-01",
    atualizado_em: "2026-04-01",
    score: 0,
  },
  {
    id: 254456,
    titulo: "Juliana Mendonça Braga Silva - Foz Spot",
    status: "open",
    valor: 0,
    nome_investidor: "Juliana Mendonça Braga Silva",
    telefone: "",
    e_mail: "",
    profissao: "",
    estado_civil: "",
    nacionalidade: "",
    cidade_onde_fica_o_imovel: "Foz do Iguaçu, PR",
    canal: "Spot Seazone",
    origem: "ManuallyCreated",
    tipo_de_venda: "",
    empreendimento: "Foz Spot",
    plano: "",
    pre_vendedor_a: "",
    deal_owner_name: "",
    data_da_reuniao: "2026-04-01",
    data_de_qualificacao: "2026-03-26",
    observacoes_longo: "Lead demonstra dúvida sobre o momento ideal para decisão, buscando entender a data limite para aproveitar melhores condições de parcelamento.",
    total_de_atividades: 7,
    atividades_concluidas: 4,
    notes_count: 3,
    numero_de_mensagens_de_e_mail: 0,
    etapa: "FUP",
    funil: "Decoração Comercial",
    negocio_criado_em: "2026-03-26",
    atualizado_em: "2026-04-01",
    score: 0,
  },
  {
    id: 255685,
    titulo: "Claudio Rengel - Foz Spot",
    status: "open",
    valor: 0,
    nome_investidor: "Claudio Rengel",
    telefone: "",
    e_mail: "claudio_rengel@hotmail.com",
    profissao: "",
    estado_civil: "",
    nacionalidade: "",
    cidade_onde_fica_o_imovel: "",
    canal: "Marketing",
    origem: "API",
    tipo_de_venda: "Interna",
    empreendimento: "Foz Spot",
    plano: "",
    pre_vendedor_a: "",
    deal_owner_name: "",
    data_da_reuniao: "2026-04-01",
    data_de_qualificacao: "2026-03-30",
    observacoes_longo: "",
    total_de_atividades: 3,
    atividades_concluidas: 2,
    notes_count: 5,
    numero_de_mensagens_de_e_mail: 0,
    etapa: "Contatados",
    funil: "Comercial SZS",
    negocio_criado_em: "2026-03-30",
    atualizado_em: "2026-04-01",
    score: 0,
  },
  {
    id: 254615,
    titulo: "Rosi Mamedio",
    status: "open",
    valor: 0,
    nome_investidor: "Rosi Mamedio",
    telefone: "",
    e_mail: "mamediorio@outlook.com",
    profissao: "",
    estado_civil: "",
    nacionalidade: "",
    cidade_onde_fica_o_imovel: "Rio de Janeiro, RJ",
    canal: "Marketing",
    origem: "API",
    tipo_de_venda: "",
    empreendimento: "",
    plano: "",
    pre_vendedor_a: "",
    deal_owner_name: "",
    data_da_reuniao: "2026-04-01",
    data_de_qualificacao: "2026-03-28",
    observacoes_longo: "",
    total_de_atividades: 7,
    atividades_concluidas: 6,
    notes_count: 11,
    numero_de_mensagens_de_e_mail: 0,
    etapa: "Introdução",
    funil: "Comercial SZS",
    negocio_criado_em: "2026-03-27",
    atualizado_em: "2026-04-01",
    score: 0,
  },
];
